# config file for the job execution on cluster 

__default__:
    account: "MutationRates"
    cpus-per-task: 1
    time: "12:00:00"
    mem: 32768
    output: "logs/{rule}-%j.out"
    error: "logs/{rule}-%j.err"

main:
    time: "02:00:00"
    mem: 16384

